version: "3"

services:
  studio:
    platform: linux/amd64
    build:
      context: .
      dockerfile: studio/config/docker/Dockerfile
    working_dir: /app
    volumes:
      - ../optinist-docker-volumes/.snakemake/:/app/.snakemake
      - ../optinist-docker-volumes/studio_data/:/app/studio_data
    ports:
      - "127.0.0.1:8000:8000"
    command: poetry run python main.py --host 0.0.0.0 --port 8000 --workers=2
    environment:
      PYTHONPATH: /app/
      TZ: Asia/Tokyo
      OPTINIST_DIR: /app/studio_data
    restart: always
